### PR TITLE
Allow linking to any file extension.

### PR DESCRIPTION
**Pull request by renatoram**
Hi, here is my rough patch for the bug I opened yesterday in Pull Request form, I hope it's useful. 

For cleaner code, I guess you could move the list of image extensions to a global setting variable, or something like that.

### CODE REVIEW

**Comment by tstaerk** [comment]
good, but this patch does more than just adding png and jpg. First of all, could you include "pdf" into the array. Then, the question generally is if we want to include as image (img src=) or as link (a href=). For PDFs I prefer a link, for images I prefer inline (img src). I will work on your patch, but my time is limited, and if you go ahead I will commit of course if the patch convinces me.

**Comment by renatoram** [comment]
As the title says, it links everything that is NOT listed in the image extensions array as "a href", and everything that IS as a "img src"... I think you read my if the other way :)

PDFs are not in the array, so they are linked as A, just like any other extension (zip, doc, whatever).

**Comment by tstaerk** [comment]
yeah, but if I merge this, PDF's will not work any longer. Or am I wrong? In case I am right, please just add your handling of images instead of replacing the handling of PDFs. Thank you, I will definitely integrate this patch. Just PDF has to keep working.

**Comment by renatoram** [comment]
PDF works just as before.

Images work just as before, even better (because even uppercase extensions are correctly recognized).

The added benefit is that .doc, .zip and all the other files work just like PDF.

Lines 66 to 69 link images (files with an extension in the array) with "img src".
Line 72 links everything else (including PDF) is still linked as "a href" as before.

**Comment by tstaerk** [comment]
yeah, I overlooked that line 72 will be executed anyway

**Comment by tstaerk** [comment]
I merged to honor your effort, thanks! Will test soon. Seems ok.

**Pull request merged**
